apiVersion: v1
kind: Namespace
metadata:
  name: infrastructures
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: services
  annotations:
    linkerd.io/inject: enabled