apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
      - name: worker
        image: worker-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: NATS_URL
          value: nats://nats.infrastructures.svc.cluster.local:4222
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: services
spec:
  selector:
    app: worker-service
  ports:
  - port: 8001