apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: infrastructures
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.51
        ports:
        - containerPort: 16686
        - containerPort: 6831
          protocol: UDP
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: infrastructures
spec:
  selector:
    app: jaeger
  ports:
  - name: query
    port: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: infrastructures
spec:
  selector:
    app: jaeger
  ports:
  - name: agent
    port: 6831
    protocol: UDP