apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: infrastructures
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'api-service'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: [services]
      relable_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: api-service
        action: keep
    - job_name: 'worker-service'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: [services]
      relable_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: worker-service
        action: keep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: infrastructures
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.48.0
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: infrastructures
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090