apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: api-service
  namespace: services
spec:
  podSelector:
    matchLabels:
      app: api-service
  port: 8000
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: api-service-authz
  namespace: services
spec:
  server:
    name: api-server
  client:
    meshTLS:
      identities:
      - "*.services.serviceaccount.identity.linkerd.cluster.local"
      - "*.infrastructures.serviceaccount.identity.linkerd.cluster.local"
---
apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: api-route
  namespace: services
spec:
  parentRefs:
  - name: api-server
    kind: Server
    group: policy.linkerd.io
  rules:
  - matches:
    - path:
      type: PathPrefix
      value: /api
    timeouts:
      request: 10s
    retry:
      attempts: 3
      backoff:
        initialDelay: 3
        backoff:
          initialDelay: 100ms
          maxDelay: 1s